/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aka.pirana.jdoc;

import aka.pirana.jdoc.model.Patient;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author aka
 */
public class JDoc extends javax.swing.JFrame {

	private static EntityManagerFactory factory ;
                private static EntityManager manager;
                private Long id;
    /**
     * Creates new form JDoc
     */
    
    public JDoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        edit_Panel = new javax.swing.JPanel();
        id_Field = new javax.swing.JTextField();
        search_Lbl = new javax.swing.JLabel();
        search_Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        consul_Btn = new javax.swing.JButton();
        create_Panel = new javax.swing.JPanel();
        idTextField = new javax.swing.JTextField();
        fnameTextField = new javax.swing.JTextField();
        lnameTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maleCheckBox = new javax.swing.JCheckBox();
        femaleCheckBox = new javax.swing.JCheckBox();
        create_Btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        telTextField = new javax.swing.JTextField();

        buttonGroup1.add(femaleCheckBox);
        buttonGroup1.add(maleCheckBox);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id_Field.setToolTipText("user ID");

        search_Lbl.setText("Search Existing Patient");

        search_Btn.setText("Search");
        search_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_BtnActionPerformed(evt);
            }
        });

        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        consul_Btn.setVisible(false);
        consul_Btn.setText("Consultation");
        consul_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consul_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edit_PanelLayout = new javax.swing.GroupLayout(edit_Panel);
        edit_Panel.setLayout(edit_PanelLayout);
        edit_PanelLayout.setHorizontalGroup(
            edit_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_PanelLayout.createSequentialGroup()
                .addGap(0, 97, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(edit_PanelLayout.createSequentialGroup()
                .addGroup(edit_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(search_Lbl)
                        .addGap(18, 18, 18)
                        .addComponent(id_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(edit_PanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(search_Btn))
                    .addGroup(edit_PanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(consul_Btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        edit_PanelLayout.setVerticalGroup(
            edit_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_PanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(edit_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_Lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(consul_Btn)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit", edit_Panel);

        idTextField.setToolTipText("id");

        fnameTextField.setToolTipText("fname");

        lnameTextField.setToolTipText("lname");

        dateTextField.setToolTipText("jj/mm/aa");

        jLabel1.setText("Unique ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Date Of Birth");

        maleCheckBox.setSelected(true);
        maleCheckBox.setText("Male");

        femaleCheckBox.setText("Female");

        create_Btn.setText("Submitt");
        create_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_BtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Tel");

        javax.swing.GroupLayout create_PanelLayout = new javax.swing.GroupLayout(create_Panel);
        create_Panel.setLayout(create_PanelLayout);
        create_PanelLayout.setHorizontalGroup(
            create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_PanelLayout.createSequentialGroup()
                .addGroup(create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(create_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(create_PanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(create_Btn))
                    .addGroup(create_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86)
                .addGroup(create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lnameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fnameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTextField)
                    .addComponent(telTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, create_PanelLayout.createSequentialGroup()
                .addGap(0, 132, Short.MAX_VALUE)
                .addComponent(maleCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaleCheckBox)
                .addGap(145, 145, 145))
        );
        create_PanelLayout.setVerticalGroup(
            create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(create_PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(create_Btn)
                        .addContainerGap())
                    .addGroup(create_PanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(create_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(femaleCheckBox)
                            .addComponent(maleCheckBox))
                        .addContainerGap(87, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Create", create_Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Edit");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_BtnActionPerformed
        Patient p = new Patient();
        
        try {
        p.setId(Long.parseLong(idTextField.getText()));
        p.setFname(fnameTextField.getText());
        p.setLname(lnameTextField.getText());
        p.setTel(telTextField.getText());
        p.setBday(parseDate(dateTextField.getText()));
        p.setGender(getGendre());
        manager.getTransaction().begin();
        manager.persist(p);
        manager.getTransaction().commit();
        resetFields();
        } catch (Exception e) {
            manager.getTransaction().rollback();
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());         
        }
    }//GEN-LAST:event_create_BtnActionPerformed
    private void resetFields(){
        idTextField.setText("");
        fnameTextField.setText("");
        lnameTextField.setText("");
        telTextField.setText("");
        dateTextField.setText("");
    }
    private void search_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_BtnActionPerformed
        if(id_Field.getText().length()>0){
            Patient patient = new Patient();
            patient = manager.find(Patient.class,Long.parseLong(id_Field.getText()));
            try{
                    System.out.println("Found"+patient.toString());
                    resultArea.setText(patient.toString());
                    consul_Btn.setVisible(true);
                    id = Long.parseLong(id_Field.getText());
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());   
            }
        }else{
             JOptionPane.showMessageDialog(this, "No ID Criteria to perform search !");   
        }
    }//GEN-LAST:event_search_BtnActionPerformed

    private void consul_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consul_BtnActionPerformed
        JConsul consult = new JConsul(id);
        consult.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_consul_BtnActionPerformed
    private String getGendre(){
      if(maleCheckBox.isEnabled()){
          return "Male";
      }else{
          return "Female";
      }
        
    }
    
    private Date parseDate(String dateStr){
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
           Date date= new Date();
           try {
               date = dateFormat.parse(dateStr);
           } catch (ParseException e) {
               e.printStackTrace();
           }
           return date;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */

        factory = Persistence.createEntityManagerFactory("jdocPU");
        manager = factory.createEntityManager();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton consul_Btn;
    private javax.swing.JButton create_Btn;
    private javax.swing.JPanel create_Panel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JPanel edit_Panel;
    private javax.swing.JCheckBox femaleCheckBox;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextField id_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lnameTextField;
    private javax.swing.JCheckBox maleCheckBox;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JButton search_Btn;
    private javax.swing.JLabel search_Lbl;
    private javax.swing.JTextField telTextField;
    // End of variables declaration//GEN-END:variables
}
